language: scala
jdk: oraclejdk8
scala:
    - 2.11.8
    - 2.12.1

script:
- sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport
- sbt coverageAggregate
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && sbt updateImpactSubmit || true'

after_success:
- bash <(curl -s https://codecov.io/bash)
